<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            ["name" => "u- channel ( 150 ) BY METERS",                                                "category_id" => 1],
            ["name" => "u- channel ( 160) / by meters",                                               "category_id" => 1],
            ["name" => "u- channel ( 180 ) by meters",                                                "category_id" => 1],
            ["name" => "u- channel ( 200 ) / by meters",                                              "category_id" => 1],
            ["name" => "u- channel ( 220 ) / by meters",                                              "category_id" => 1],
            ["name" => "u- channel ( 240 ) / by meters",                                              "category_id" => 1],
            ["name" => "u- channel ( 250 ) / by meters",                                              "category_id" => 1],
            ["name" => "u- channel ( 260 ) by meters",                                                "category_id" => 1],
            ["name" => "u- channel ( 280 ) by meters",                                                "category_id" => 1],
            ["name" => "u- channel ( 300 ) by meters",                                                "category_id" => 1],
            ["name" => "u- channel ( 350 ) by meters",                                                "category_id" => 1],
            ["name" => "u- channel ( 380 ) by meters",                                                "category_id" => 1],
            ["name" => "Varisco 1 serial ( ITH0009806 ) ",                                            "category_id" => 1],
            ["name" => "Varisco 2 serial ( ITH0009631 ) ",                                            "category_id" => 1],
            ["name" => "Varisco 3 serial ( ITH000637 ) ",                                             "category_id" => 1],
            ["name" => "Oasis  3 serial ( 20140 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 1 serial ( 20168 ) ",                                                   "category_id" => 1],
            ["name" => "Oasis 10 serial ( 21492 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 11 serial ( 21495 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 12 serial ( 21493 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 13 serial ( 21490 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 14 serial ( 21489 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 15 serial ( 21494 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 16 serial ( 21767 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 17 serial ( 21758 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 18 serial ( 21769 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 19 serial ( 21762 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 2 serial ( 20130 )",                                                    "category_id" => 1],
            ["name" => "Oasis 20 serial ( 21764 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 21 serial ( 21768 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 22 serial ( 21763 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 23 serial ( 21765 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 24 serial ( 21760 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 25 serial ( 21766 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 26 serial ( 21862 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 27 serial ( 21859 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 28 serial ( 21918 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 29 serial ( 21858 ) ",                                                  "category_id" => 1],
            ["name" => "Oasis 4 serial ( 20259 ) ",                                                   "category_id" => 1],
            ["name" => "Oasis 5 serial ( 20131 ) ",                                                   "category_id" => 1],
            ["name" => "Oasis 6 serial ( 20142 ) ",                                                   "category_id" => 1],
            ["name" => "Oasis 7 serial ( 20167 ) ",                                                   "category_id" => 1],
            ["name" => "Oasis 8 serial ( 21496 ) ",                                                   "category_id" => 1],
            ["name" => "Oasis 9 serial ( 21491 ) ",                                                   "category_id" => 1],
            ["name" => "Hudig 1 serial ( 19677 ) ",                                                   "category_id" => 1],
            ["name" => "Hudig 2 serial ( 19539 ) ",                                                   "category_id" => 1],
            ["name" => "Hudig 3 serial ( 19610 ) ",                                                   "category_id" => 1],
            ["name" => "Hudig 4 serial ( 19674 ) ",                                                   "category_id" => 1],
            ["name" => "Hudig 5 serial ( B2451686 ) ",                                                "category_id" => 1],
            ["name" => "Hudig 6 ( 21473 ) ",                                                          "category_id" => 1],
            ["name" => "Hudig 7 serial ( 21471 ) ",                                                   "category_id" => 1],
            ["name" => "Hudig 8 serial ( 21467 ) ",                                                   "category_id" => 1],
            ["name" => "Hudig 9 serial ( 21469 ) ",                                                   "category_id" => 1],
            ["name" => "Geho 1 serial ( 12-2-004 )",                                                  "category_id" => 1],
            ["name" => "Geho 10 ( 160446 ) ",                                                         "category_id" => 1],
            ["name" => "Geho 11 SCRAP  ( 160352 )",                                                   "category_id" => 1],
            ["name" => "Geho 12 serial ( 160349 )",                                                   "category_id" => 1],
            ["name" => "Geho 13 serial ( 160445 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 14 serial ( 160441 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 15 serial ( 160347 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 16 serial ( 160346 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 17 ( 160449 ) ",                                                         "category_id" => 1],
            ["name" => "Geho 18 serial ( 160351 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 19 serial ( 160348 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 2 serial ( 12-2-006 )",                                                  "category_id" => 1],
            ["name" => "Geho 20 serial ( 160448 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 21 serial ( 160350 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 22 serial ( 160444 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 23 serial ( 160447 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 24 serial ( 160324 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 25 serial ( 160325 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 26 serial ( 160322 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 27 serial ( 160443 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 28 serial ( 160353 ) ",                                                  "category_id" => 1],
            ["name" => "Geho 3 serial ( 02-2-0042/7 )",                                               "category_id" => 1],
            ["name" => "Geho 4 serial ( 01-2-0026/2 ) ",                                              "category_id" => 1],
            ["name" => "Geho 5 serial ( 07-2-0002/2 )",                                               "category_id" => 1],
            ["name" => "Geho 6 serial ( 01-2-0026/7 ) ",                                              "category_id" => 1],
            ["name" => "Geho 7 serial ( 01-2-0038/4 ) ",                                              "category_id" => 1],
            ["name" => "Geho 8 serial ( 160442 )",                                                    "category_id" => 1],
            ["name" => "Geho 9 serial ( 160354 )",                                                    "category_id" => 1],
            ["name" => "Baifa Generator- ( 1709041 )- KVA ( 94 ) NO(2)",                              "category_id" => 1],
            ["name" => "Baifa Generator- ( 1709044 )- KVA ( 94 ) NO(6)",                              "category_id" => 1],
            ["name" => "Baifa Generator-( 140418E )- KVA ( 115 ) NO (3)",                             "category_id" => 1],
            ["name" => "Baifa Generator-( 140421E )- KVA ( 115 ) NO(4)",                              "category_id" => 1],
            ["name" => "Baifa Generator-( 141113E )- KVA ( 160 ) NO(1)",                              "category_id" => 1],
            ["name" => "Baifa Generator-( 1805139 )- KVA ( 156) NO( 5 )",                             "category_id" => 1],
            ["name" => "I-Beams ( 248 ) / by meters",                                                 "category_id" => 1],
            ["name" => "I-Beams ( 250 ) / by meters",                                                 "category_id" => 1],
            ["name" => "I-Beams ( 298 ) BY METERS",                                                   "category_id" => 1],
            ["name" => "I-Beams ( 300 ) BY METERS",                                                   "category_id" => 1],
            ["name" => "I-Beams ( 348 ) / by meters",                                                 "category_id" => 1],
            ["name" => "I-Beams ( 350 ) / by meters",                                                 "category_id" => 1],
            ["name" => "I-Beams ( 396 ) / by meters",                                                 "category_id" => 1],
            ["name" => "I-Beams ( 400 ) / by meters",                                                 "category_id" => 1],
            ["name" => "Timber 10*10*3M (By Psc)",                                                    "category_id" => 1],
            ["name" => "Timber 10*10*4M (By Psc)",                                                    "category_id" => 1],
            ["name" => "Timber 4*20*3M (By Psc)",                                                     "category_id" => 1],
            ["name" => "Timber 4*20*4M (By Psc)",                                                     "category_id" => 1],
            ["name" => "Timber 7*7*3M (By Psc)",                                                      "category_id" => 1],
            ["name" => "Timber 7*7*4M (By Psc)",                                                      "category_id" => 1],
            ["name" => "Controls 7.5 H",                                                              "category_id" => 1],
            ["name" => "Controls 10 H",                                                               "category_id" => 1],
            ["name" => "Controls Scrap",                                                              "category_id" => 1],
            ["name" => "Controls Tormaic 10 H ",                                                      "category_id" => 1],
            ["name" => "Controls Tormaic 15 H ",                                                      "category_id" => 1],
            ["name" => "Controls Tormaic 7.5 H ",                                                     "category_id" => 1],
            ["name" => "Controls Tsurimi 7.5 H ",                                                     "category_id" => 1],
            ["name" => "Controls Tsurimi 15 H ",                                                      "category_id" => 1],
            ["name" => "riser pvc pipe ( SCRAP ) 3m /3 inch",                                         "category_id" => 1],
            ["name" => "riser pvc pipe 3m /3 inch",                                                   "category_id" => 1],
            ["name" => "Acetylen Cylinder",                                                           "category_id" => 1],
            ["name" => "Oxygen Cylinder",                                                             "category_id" => 1],
            ["name" => "Submersible water Tsurimi  1.5 HP",                                           "category_id" => 1],
            ["name" => "Submersible water Tsurimi   2 HP",                                            "category_id" => 1],
            ["name" => "Submersible water Tsurimi   2.5 HP",                                          "category_id" => 1],
            ["name" => "Submersible water Tsurimi   3 HP",                                            "category_id" => 1],
            ["name" => "Submersible water Tsurimi  5 HP",                                             "category_id" => 1],
            ["name" => "Submersible water Tsurimi  6 HP",                                             "category_id" => 1],
            ["name" => "Submersible Water Tsurimi 7.5 HP",                                            "category_id" => 1],
            ["name" => "Submersible water Tsurimi   10 HP",                                           "category_id" => 1],
            ["name" => "Submersible water Tsurimi 15 HP",                                             "category_id" => 1],
            ["name" => "Teeth for ABI head ( Used )",                                                 "category_id" => 1],
            ["name" => "Teeth for ABI head(Brand new)",                                               "category_id" => 1],
            ["name" => "Top Adaptor (DWs)",                                                           "category_id" => 1],
            ["name" => "Bottom Adaptor (DWs)",                                                        "category_id" => 1],
            ["name" => "Cable-4mm / By meters Armond",                                                "category_id" => 1],
            ["name" => "Cable-6mm / By meters Armond",                                                "category_id" => 1],
            ["name" => "Cable-8mm / By meters Armond",                                                "category_id" => 1],
            ["name" => "Cable-10mm / By meters Armond",                                               "category_id" => 1],
            ["name" => "Cable-16mm / By meters Armond",                                               "category_id" => 1],
            ["name" => "Cable-20mm / By meters Armond",                                               "category_id" => 1],
            ["name" => "Cable-25mm / By meters Armond",                                               "category_id" => 1],
            ["name" => "Cable-70mm / By meters Armond",                                               "category_id" => 1],
            ["name" => "cable -75mm / By meters Armond",                                              "category_id" => 1],
            ["name" => "cable -85 mm / By meters Armond",                                             "category_id" => 1],
            ["name" => "cable -95mm / By meters Armond",                                              "category_id" => 1],
            ["name" => "Cable-120mm / By meters Armond",                                              "category_id" => 1],
            ["name" => "Cable-150mm / By meters Armond",                                              "category_id" => 1],
            ["name" => "Compactor jumper",                                                            "category_id" => 1],
            ["name" => "Compactor plate",                                                             "category_id" => 1],
            ["name" => "Compactor roller",                                                            "category_id" => 1],
            ["name" => "Cutting disc",                                                                "category_id" => 1],
            ["name" => "Cutting grinder",                                                             "category_id" => 1],
            ["name" => "Cutting grinder BIG ",                                                        "category_id" => 1],
            ["name" => "Cutting set",                                                                 "category_id" => 1],
            ["name" => "Deep wells pumps 4.5 HP",                                                     "category_id" => 1],
            ["name" => "Deepwells pumps 5.5 HP",                                                      "category_id" => 1],
            ["name" => "Deepwells pumps 6 HP",                                                        "category_id" => 1],
            ["name" => "Deepwells pumps 7.5 H",                                                       "category_id" => 1],
            ["name" => "Deepwells pumps 10 H",                                                        "category_id" => 1],
            ["name" => "Deepwells pumps 12.5 H",                                                      "category_id" => 1],
            ["name" => "Deepwells pumps 15 H",                                                        "category_id" => 1],
            ["name" => "lay-flat Blue discharge hose 2 inch / by meters",                             "category_id" => 1],
            ["name" => "lay-flat Blue discharge hose 3 inch / by meters",                             "category_id" => 1],
            ["name" => "lay-flat Blue discharge hose 4 inch / by meters",                             "category_id" => 1],
            ["name" => "lay-flat Blue discharge hose 6 inch / by meters",                             "category_id" => 1],
            ["name" => "lay-flat Blue discharge hose 8 inch / by meters",                             "category_id" => 1],
            ["name" => "Scaffolding",                                                                 "category_id" => 1],
            ["name" => "Wood saw ( chainsaw )",                                                       "category_id" => 1],
            ["name" => "Wood saw ( Table )",                                                          "category_id" => 1],
            ["name" => "Adapter For ABI ( Brand New ) ",                                              "category_id" => 1],
            ["name" => "Adapter For Klemm ( Brand New ) ",                                            "category_id" => 1],
            ["name" => "Air left  pipe 6m /2 inch",                                                   "category_id" => 1],
            ["name" => "black hose 1.5 inch by meters",                                               "category_id" => 1],
            ["name" => "Black armored suction hose 3 inch / by meters",                               "category_id" => 1],
            ["name" => "Black armored suction hose 4 inch / by meters",                               "category_id" => 1],
            ["name" => "Black armond suction hose 6 inch / by meters",                                "category_id" => 1],
            ["name" => "Black armond suction hose 8 inch / by meters",                                "category_id" => 1],
            ["name" => "Change over",                                                                 "category_id" => 1],
            ["name" => "Clips 2 inch",                                                                "category_id" => 1],
            ["name" => "Clips 3 inch",                                                                "category_id" => 1],
            ["name" => "Clips 4 inch",                                                                "category_id" => 1],
            ["name" => "Clips 6 inch",                                                                "category_id" => 1],
            ["name" => "Clips 8 inch",                                                                "category_id" => 1],
            ["name" => "Clips 10 inch",                                                               "category_id" => 1],
            ["name" => "Concret saw cutter",                                                          "category_id" => 1],
            ["name" => "Fire extinguisher 7.5 Kilo",                                                  "category_id" => 1],
            ["name" => "Fire extinguisher 10 Kilo",                                                   "category_id" => 1],
            ["name" => "flexibol armond-hose 2 inch",                                                 "category_id" => 1],
            ["name" => "flexibol armond-hose 3 inch",                                                 "category_id" => 1],
            ["name" => "flexibol armond-hose 4 inch",                                                 "category_id" => 1],
            ["name" => "flexibol armond-hose 6 inch",                                                 "category_id" => 1],
            ["name" => "Gray pvc pipe 6m / 2 inch",                                                   "category_id" => 1],
            ["name" => "Gray pvc pipe 6m / 6 inch",                                                   "category_id" => 1],
            ["name" => "JCB ( 2008 ) - plate number = 1708",                                          "category_id" => 1],
            ["name" => "JCB ( 2016 ) - plate number = 30409",                                         "category_id" => 1],
            ["name" => "Jetting pipe 6 M",                                                            "category_id" => 1],
            ["name" => "Jetting pipe 3 M ",                                                           "category_id" => 1],
            ["name" => "Level ",                                                                      "category_id" => 1],
            ["name" => "Total Station",                                                               "category_id" => 1],
            ["name" => "Steel SOCKET 3  inch",                                                        "category_id" => 1],
            ["name" => "Steel SOCKET 4  inch",                                                        "category_id" => 1],
            ["name" => "Steel SOCKET 6  inch",                                                        "category_id" => 1],
            ["name" => "steel Coupler 2 inch without Clabs",                                          "category_id" => 1],
            ["name" => "steel Coupler 2 inch with Clabs",                                             "category_id" => 1],
            ["name" => "Cable-4mm / By meters ",                                                      "category_id" => 1],
            ["name" => "Cable-6mm / By meters ",                                                      "category_id" => 1],
            ["name" => "Cable-8mm / By meters ",                                                      "category_id" => 1],
            ["name" => "Cable-10mm / By meters ",                                                     "category_id" => 1],
            ["name" => "Cable-16mm / By meters ",                                                     "category_id" => 1],
            ["name" => "blue pvc pipe 6m / 8 inch Casing",                                            "category_id" => 1],
            ["name" => "blue pvc pipe 6m / 10 inch Casing",                                           "category_id" => 1],
            ["name" => "blue pvc pipe 6m / 6 inch ",                                                  "category_id" => 1],
            ["name" => "Header Pipe Steel  3m / 6 inch",                                              "category_id" => 1],
            ["name" => "Header Pipe  Steel 6m / 6 inch",                                              "category_id" => 1],
            ["name" => "botix",                                                                       "category_id" => 1],
            ["name" => "Bobcat ( 2016 ) - plate number = ( 30408 )",                                  "category_id" => 1],
            ["name" => "Anchoring machine Cassagrrande 140 serial ( ATZ 0140 ) ",                     "category_id" => 1],
            ["name" => "Anchoring machine Cassagrrande 141 serial ( ATZ 0141 ) ",                     "category_id" => 1],
            ["name" => "Anchoring machine Klemm 803 serial ( 51105 ) ",                               "category_id" => 1],
            ["name" => "Anchoring machine Klemm 806 serial ( 65583 ) ",                               "category_id" => 1],
            ["name" => "Anchoring machine (C - 6)",                                                   "category_id" => 1],
            ["name" => "Sennebogen SL TM 13/16 Year 2009 serial ( 5356791 ) ",                        "category_id" => 1],
            ["name" => "Sennebogen TM 13/16 Year 2003 serial ( 5356622 ) ",                           "category_id" => 1],
            ["name" => "Liebherr RE 942 Year 1998 serial ( 3822-0180 ) ",                             "category_id" => 1],
            ["name" => "O&K RH9 Year 1996 serial ( 58071 ) ",                                         "category_id" => 1],
            ["name" => "Zeppelin TM 12/15 Year 1997 serial ( 5286353 ) ",                             "category_id" => 1],
            ["name" => "Water tank steel 1m*2m",                                                      "category_id" => 1],
            ["name" => "Water tank steel 2m*3m",                                                      "category_id" => 1],
            ["name" => "Drip tray",                                                                   "category_id" => 1],
            ["name" => "803 ( Swivel ) used",                                                         "category_id" => 1],
            ["name" => "ABB pump ( black NO 1 ) ",                                                    "category_id" => 1],
            ["name" => "ABB pump ( black NO 2 ) ",                                                    "category_id" => 1],
            ["name" => "ABB pump ( Blue )",                                                           "category_id" => 1],
            ["name" => "ABB Pump (Gray)",                                                             "category_id" => 1],
            ["name" => "ABB pump Brand New ( black NO 3 ) ",                                          "category_id" => 1],
            ["name" => "ABB pump Brand New ( black NO 4 ) ",                                          "category_id" => 1],
            ["name" => "ABI drill ( black hose / 1.5 inch ) new",                                     "category_id" => 1],
            ["name" => "ABI Flight adaptor ( new ) ",                                                 "category_id" => 1],
            ["name" => "ABI hummer ( big plug hose ) new",                                            "category_id" => 1],
            ["name" => "ABI hummer ( chain ) new",                                                    "category_id" => 1],
            ["name" => "ABI hummer ( hose base ) new",                                                "category_id" => 1],
            ["name" => "ABI hummer ( hose base ) used",                                               "category_id" => 1],
            ["name" => "ABI hummer ( slide guide ) new",                                              "category_id" => 1],
            ["name" => "ABI hummer ( slide guide ) used",                                             "category_id" => 1],
            ["name" => "ABI hummer ( small plug hose ) used",                                         "category_id" => 1],
            ["name" => "ABI rockroller / 6 inch ( used )",                                            "category_id" => 1],
            ["name" => "air compresor Maintenance car",                                               "category_id" => 1],
            ["name" => "Air Compressor",                                                              "category_id" => 1],
            ["name" => "Barrel (Brand new)",                                                          "category_id" => 1],
            ["name" => "Barrel (USED)",                                                               "category_id" => 1],
            ["name" => "battery Charger ",                                                            "category_id" => 1],
            ["name" => "BIG ABB pump (white)",                                                        "category_id" => 1],
            ["name" => "BIG Manuel Tension  Jack big (blue)",                                         "category_id" => 1],
            ["name" => "Big Nail to clamp ( new ) ",                                                  "category_id" => 1],
            ["name" => "casing ( swivel ) USED",                                                      "category_id" => 1],
            ["name" => "Casing converter 3 INCH",                                                     "category_id" => 1],
            ["name" => "Casing flange 2 inch",                                                        "category_id" => 1],
            ["name" => "Casing flange 3 inch",                                                        "category_id" => 1],
            ["name" => "Casing flange 5 inch",                                                        "category_id" => 1],
            ["name" => "casing head 2 INCH",                                                          "category_id" => 1],
            ["name" => "casing head 2 INCH BRAND NEW",                                                "category_id" => 1],
            ["name" => "casing head 5 INCH",                                                          "category_id" => 1],
            ["name" => "casing head 5 INCH Brand new",                                                "category_id" => 1],
            ["name" => "casing head 5 INCH scrap",                                                    "category_id" => 1],
            ["name" => "Casing pipe / 2 inch",                                                        "category_id" => 1],
            ["name" => "Casing pipe 2M / 2 inch",                                                     "category_id" => 1],
            ["name" => "casing pipes 5 brand new",                                                    "category_id" => 1],
            ["name" => "casing pipes 5 inch ",                                                        "category_id" => 1],
            ["name" => "casing pipes 5 INCH scrap",                                                   "category_id" => 1],
            ["name" => "Casing Teeth Brand New",                                                      "category_id" => 1],
            ["name" => "Colton Electric Welding machine ( 1 )Blue ",                                  "category_id" => 1],
            ["name" => "Colton Electric Welding machine ( 2 )Blue ",                                  "category_id" => 1],
            ["name" => "Colton Electric Welding machine ( 3 )Blue ",                                  "category_id" => 1],
            ["name" => "Colton Electric Welding machine ( 4 )Blue ",                                  "category_id" => 1],
            ["name" => "Colton Electric Welding machine ( 5 )Blue ",                                  "category_id" => 1],
            ["name" => "Colton Electric Welding machine ( 6 )Blue ",                                  "category_id" => 1],
            ["name" => "Colton Electric Welding machine ( 7 )Blue ",                                  "category_id" => 1],
            ["name" => "Colton Electric Welding machine ( 8 )Blue ",                                  "category_id" => 1],
            ["name" => "Colton Electric Welding machine ( 9 ) Blue",                                  "category_id" => 1],
            ["name" => "Colton Electric Welding machine Blue SCRAP",                                  "category_id" => 1],
            ["name" => "Colton Electric Welding machine SCRAP ",                                      "category_id" => 1],
            ["name" => "Compressor air man",                                                          "category_id" => 1],
            ["name" => "converter casing 2 inch",                                                     "category_id" => 1],
            ["name" => "converter casing 3 inch",                                                     "category_id" => 1],
            ["name" => "Converter Flight C-6",                                                        "category_id" => 1],
            ["name" => "copper water valve / 3 inch ( new )",                                         "category_id" => 1],
            ["name" => "DB",                                                                          "category_id" => 1],
            ["name" => "DB of DWs pump 10hp",                                                         "category_id" => 1],
            ["name" => "DB of DWs pump 7.5hp",                                                        "category_id" => 1],
            ["name" => "Diesel Steel tank 2500 L ",                                                   "category_id" => 1],
            ["name" => "Diesel tank in yard",                                                         "category_id" => 1],
            ["name" => "Diesl Grout machine",                                                         "category_id" => 1],
            ["name" => "door lock ( new )",                                                           "category_id" => 1],
            ["name" => "Drill JCB",                                                                   "category_id" => 1],
            ["name" => "Drill liebherr ",                                                             "category_id" => 1],
            ["name" => "Drill O&K",                                                                   "category_id" => 1],
            ["name" => "Drill sennebogen",                                                            "category_id" => 1],
            ["name" => "Drill sennebogen SL",                                                         "category_id" => 1],
            ["name" => "Drill Small",                                                                 "category_id" => 1],
            ["name" => "Drill Stand",                                                                 "category_id" => 1],
            ["name" => "Drill zeppelin",                                                              "category_id" => 1],
            ["name" => "Drilling head  Anchoring ",                                                   "category_id" => 1],
            ["name" => "Drilling head  Anchoring (Brand new) ",                                       "category_id" => 1],
            ["name" => "Drilling head  Anchoring (SCRAP)",                                            "category_id" => 1],
            ["name" => "Drilling head  Anchoring (Small size)",                                       "category_id" => 1],
            ["name" => "Drilling head ABI",                                                           "category_id" => 1],
            ["name" => "Drilling head ABI (SCRAP)",                                                   "category_id" => 1],
            ["name" => "Drilling head adapter 10m / 17  inch",                                        "category_id" => 1],
            ["name" => "Drilling head adapter 6m / 12  inch",                                         "category_id" => 1],
            ["name" => "Drilling head adapter 6m / 17  inch",                                         "category_id" => 1],
            ["name" => "Drilling head liebherr",                                                      "category_id" => 1],
            ["name" => "Drilling head sennebogen",                                                    "category_id" => 1],
            ["name" => "Drilling head sennebogen SL",                                                 "category_id" => 1],
            ["name" => "Drilling head zeppelin",                                                      "category_id" => 1],
            ["name" => "Electric grout machine",                                                      "category_id" => 1],
            ["name" => "Electric Hoist Pulley",                                                       "category_id" => 1],
            ["name" => "Electric Lubricated",                                                         "category_id" => 1],
            ["name" => "Electric motor / 10 HP Brand New",                                            "category_id" => 1],
            ["name" => "Electric motor / 10 HP scrap",                                                "category_id" => 1],
            ["name" => "Electric motor / 7.5 HP scrap",                                               "category_id" => 1],
            ["name" => "Electric motors 1.5 HP",                                                      "category_id" => 1],
            ["name" => "Electric Tension  Jack ( 1 ) green",                                          "category_id" => 1],
            ["name" => "Electric Tension  Jack ( 2 ) red",                                            "category_id" => 1],
            ["name" => "Electric Tension  Jack ( 3 ) green",                                          "category_id" => 1],
            ["name" => "Electric Tension  Jack ( 4 ) Blue (Brand new)",                               "category_id" => 1],
            ["name" => "Electric Tension  Jack Green SCRAP",                                          "category_id" => 1],
            ["name" => "Electric Tension  Jack red SCRAP",                                            "category_id" => 1],
            ["name" => "Electric Tension  Jack Yellow",                                               "category_id" => 1],
            ["name" => "Electric Welding machine (green) - big - old /Scrap",                         "category_id" => 1],
            ["name" => "Electric Welding machine (Red) - big - old /Scrap",                           "category_id" => 1],
            ["name" => "Flange anchoring 141",                                                        "category_id" => 1],
            ["name" => "Flange anchoring 803",                                                        "category_id" => 1],
            ["name" => "Flange anchoring 806",                                                        "category_id" => 1],
            ["name" => "Flight liebherr",                                                             "category_id" => 1],
            ["name" => "Flight sennebogen",                                                           "category_id" => 1],
            ["name" => "Flight sennebogen SL",                                                        "category_id" => 1],
            ["name" => "Flight zeppelin",                                                             "category_id" => 1],
            ["name" => "Flights  Anchoring 1.5m",                                                     "category_id" => 1],
            ["name" => "FLIGHTS ABI",                                                                 "category_id" => 1],
            ["name" => "FLIGHTS ABI (SCRAP)",                                                         "category_id" => 1],
            ["name" => "Flights anchor to liebherr",                                                  "category_id" => 1],
            ["name" => "Flights anchoring",                                                           "category_id" => 1],
            ["name" => "Flights anchoring (SCRAP)",                                                   "category_id" => 1],
            ["name" => "flights anchoring 2.5m",                                                      "category_id" => 1],
            ["name" => "flights anchoring 2m",                                                        "category_id" => 1],
            ["name" => "Flights Lock",                                                                "category_id" => 1],
            ["name" => "Flights Lock (Brand new)",                                                    "category_id" => 1],
            ["name" => "Gasoline Generator  ( Subaru )-serial ( RGX2900 )",                           "category_id" => 1],
            ["name" => "Gasoline Generator (SCRAP) ( Subaru )-serial ( RGX3600 )",                    "category_id" => 1],
            ["name" => "Hillty ",                                                                     "category_id" => 1],
            ["name" => "Hilti",                                                                       "category_id" => 1],
            ["name" => "Hudig or Oasis ( oil pump ) new",                                             "category_id" => 1],
            ["name" => "Hummer liebherr",                                                             "category_id" => 1],
            ["name" => "Hummer O&K",                                                                  "category_id" => 1],
            ["name" => "Hummer sennebogen",                                                           "category_id" => 1],
            ["name" => "Hummer sennebogen SL",                                                        "category_id" => 1],
            ["name" => "Hummer zeppelin",                                                             "category_id" => 1],
            ["name" => "Jack Hummer JCB",                                                             "category_id" => 1],
            ["name" => "JCB ( A/ C ) SCRAP",                                                          "category_id" => 1],
            ["name" => "JCB ( Bucket ) 30cm used",                                                    "category_id" => 1],
            ["name" => "JCB ( drilling head ) USED",                                                  "category_id" => 1],
            ["name" => "JCB ( FORK ) used",                                                           "category_id" => 1],
            ["name" => "JCB ( swivel ) USED",                                                         "category_id" => 1],
            ["name" => "Klemm 803 ( hydraulic pump ) used",                                           "category_id" => 1],
            ["name" => "Klemm 803 ( hydraulic valve ) scrap",                                         "category_id" => 1],
            ["name" => "Klemm 806 ( drill valve ) scrap",                                             "category_id" => 1],
            ["name" => "Klemm 806 ( hydraulic pump ) used",                                           "category_id" => 1],
            ["name" => "Klemm 806 or 803 ( flange hydraulic pump ) new",                              "category_id" => 1],
            ["name" => "klemm drilling teeth (Brand new)",                                            "category_id" => 1],
            ["name" => "Klemm flushing Flights",                                                      "category_id" => 1],
            ["name" => "Klemm flushing Flights (SCRAP ) 3 inch",                                      "category_id" => 1],
            ["name" => "Klemm flushing Flights 3 inch",                                               "category_id" => 1],
            ["name" => "Klemm flushing head",                                                         "category_id" => 1],
            ["name" => "Klemm flushing head 3 INCH",                                                  "category_id" => 1],
            ["name" => "Klemm flushing head 3 INCH (BRAND NEW)",                                      "category_id" => 1],
            ["name" => "Klemm flushing head 3 INCH (SCRAP)",                                          "category_id" => 1],
            ["name" => "liebherr ( clamp teeth ) used",                                               "category_id" => 1],
            ["name" => "liebherr ( Drill gear set ) new",                                             "category_id" => 1],
            ["name" => "liebherr ( Drill gear set ) scrap",                                           "category_id" => 1],
            ["name" => "liebherr ( drill motor ) scrap",                                              "category_id" => 1],
            ["name" => "liebherr ( hydraulic pump ) scrap",                                           "category_id" => 1],
            ["name" => "liebherr ( Idler ) used",                                                     "category_id" => 1],
            ["name" => "liebherr ( Track pump ) used",                                                "category_id" => 1],
            ["name" => "liebherr (drill motor ) new",                                                 "category_id" => 1],
            ["name" => "linkolin Diesel welding machine  NO ( 1 )",                                   "category_id" => 1],
            ["name" => "linkolin Diesel welding machine  NO ( 2 ) ",                                  "category_id" => 1],
            ["name" => "linkolin Diesel welding machine  NO ( 3 ) ",                                  "category_id" => 1],
            ["name" => "Lorch Electric Welding machine red -small SCRAP",                             "category_id" => 1],
            ["name" => "lowbed ( door handle ) new",                                                  "category_id" => 1],
            ["name" => "lowbed ( dynamo ) new",                                                       "category_id" => 1],
            ["name" => "lowbed ( water pump ) scrap",                                                 "category_id" => 1],
            ["name" => "Maintenance car / ISUZU - plate number = 15/1573",                            "category_id" => 1],
            ["name" => "Manual Lubricated",                                                           "category_id" => 1],
            ["name" => "Manuel Tension  Jack (blue)",                                                 "category_id" => 1],
            ["name" => "MAZDA ( A / C ) SCRAP",                                                       "category_id" => 1],
            ["name" => "Miller Diesel Welding machine / Scrap",                                       "category_id" => 1],
            ["name" => "Miller Diesel welding machine NO ( 4 ) SCRAP",                                "category_id" => 1],
            ["name" => "Miller Diesel welding machine NO ( 5 ) ",                                     "category_id" => 1],
            ["name" => "Mouth steel pipe 10m",                                                        "category_id" => 1],
            ["name" => "Mouth steel pipe 6m",                                                         "category_id" => 1],
            ["name" => "MZA-140 & 141 ( bering drill ) NEW ",                                         "category_id" => 1],
            ["name" => "MZA-140 & 141 ( bering drill ) USED",                                         "category_id" => 1],
            ["name" => "MZA-140 ( Hyd./Elc. valve + cable ) new",                                     "category_id" => 1],
            ["name" => "MZA-140 ( safety wire ) used",                                                "category_id" => 1],
            ["name" => "MZA-141 ( safety arm ) used",                                                 "category_id" => 1],
            ["name" => "O&K ( CONTROL ) SCRAP",                                                       "category_id" => 1],
            ["name" => "O&K ( control valve ) used",                                                  "category_id" => 1],
            ["name" => "O&K ( drill motor ) used",                                                    "category_id" => 1],
            ["name" => "O&K ( safety boom ) new",                                                     "category_id" => 1],
            ["name" => "O&K ( Track motor ) scrap",                                                   "category_id" => 1],
            ["name" => "O&K swivel ( 6m) ",                                                           "category_id" => 1],
            ["name" => "O&K swivel (10m) ",                                                           "category_id" => 1],
            ["name" => "Old Compressor ( Red)",                                                       "category_id" => 1],
            ["name" => "Old Tension  Jack  Yellow ( Scrap )",                                         "category_id" => 1],
            ["name" => "Orange plastic pipe 6m / 8 inch",                                             "category_id" => 1],
            ["name" => "Ouger (ABI)",                                                                 "category_id" => 1],
            ["name" => "Oxygen ( flashback arrestor ) used",                                          "category_id" => 1],
            ["name" => "Pick-up Nissan Zour - plate number = 1/70894",                                "category_id" => 1],
            ["name" => "pipe wrench",                                                                 "category_id" => 1],
            ["name" => "Plant grout machine",                                                         "category_id" => 1],
            ["name" => "Plastic Valve 6 inch",                                                        "category_id" => 1],
            ["name" => "plug Hudig with clips / 6 inch",                                              "category_id" => 1],
            ["name" => "plug Hudig without clips / 6 inch",                                           "category_id" => 1],
            ["name" => "plug Oasis with clips / 6 inch",                                              "category_id" => 1],
            ["name" => "plug Oasis without clips / 6 inch",                                           "category_id" => 1],
            ["name" => "Pressure Gauges Calibration",                                                 "category_id" => 1],
            ["name" => "PVC  SOCKET 2  inch",                                                         "category_id" => 1],
            ["name" => "PVC  SOCKET 4  inch",                                                         "category_id" => 1],
            ["name" => "PVC  SOCKET 6  inch",                                                         "category_id" => 1],
            ["name" => "PVC ( T ) 2  inch",                                                           "category_id" => 1],
            ["name" => "PVC ( T ) 6  inch",                                                           "category_id" => 1],
            ["name" => "PVC elbow 2  inch",                                                           "category_id" => 1],
            ["name" => "PVC elbow 6  inch",                                                           "category_id" => 1],
            ["name" => "PVC SOCKET / 10 INCH ( NEW ) ",                                               "category_id" => 1],
            ["name" => "Rhino-D Diesel Welding machine / NO ( 6 )",                                   "category_id" => 1],
            ["name" => "Safety 803 or 806",                                                           "category_id" => 1],
            ["name" => "sennebogen  ( hammer motor ) used",                                           "category_id" => 1],
            ["name" => "sennebogen ( Boom aluminum safety ) new",                                     "category_id" => 1],
            ["name" => "sennebogen ( crane wire Pulley ) used",                                       "category_id" => 1],
            ["name" => "sennebogen ( Electric valve ) new",                                           "category_id" => 1],
            ["name" => "sennebogen ( Electric valve ) used",                                          "category_id" => 1],
            ["name" => "sennebogen ( exhaust ) used",                                                 "category_id" => 1],
            ["name" => "sennebogen ( hammer .rubber ) new",                                           "category_id" => 1],
            ["name" => "sennebogen ( hammer .rubber ) used",                                          "category_id" => 1],
            ["name" => "sennebogen ( hammer clamp ) new",                                             "category_id" => 1],
            ["name" => "sennebogen ( hammer motor ) new",                                             "category_id" => 1],
            ["name" => "sennebogen ( Lower wire Pulley ) used",                                       "category_id" => 1],
            ["name" => "sennebogen ( small track roller ) scrap",                                     "category_id" => 1],
            ["name" => "sennebogen ( small track roller ) used",                                      "category_id" => 1],
            ["name" => "sennebogen ( Upper wire Pulley ) scrap",                                      "category_id" => 1],
            ["name" => "sennebogen SL ( Drill gear set ) SCRAP",                                      "category_id" => 1],
            ["name" => "Sheet Pile ( 600 ) BY METER",                                                 "category_id" => 1],
            ["name" => "Small ABB ( White )",                                                         "category_id" => 1],
            ["name" => "Spacer",                                                                      "category_id" => 1],
            ["name" => "Stand For Strand",                                                            "category_id" => 1],
            ["name" => "steel ( T ) 3  inch",                                                         "category_id" => 1],
            ["name" => "steel ( T ) 6  inch",                                                         "category_id" => 1],
            ["name" => "steel ( T ) geho 6  inch",                                                    "category_id" => 1],
            ["name" => "steel ( T ) Hudig  6  inch",                                                  "category_id" => 1],
            ["name" => "steel ( T ) Oasis  6  inch",                                                  "category_id" => 1],
            ["name" => "steel ( T ) Varisco  6  inch",                                                "category_id" => 1],
            ["name" => "Steel 20mm",                                                                  "category_id" => 1],
            ["name" => "steel coupler Geho / 6 inch",                                                 "category_id" => 1],
            ["name" => "steel coupler Hudig /6 inch",                                                 "category_id" => 1],
            ["name" => "steel Coupler Oasis with clips / 6 inch ",                                    "category_id" => 1],
            ["name" => "steel Coupler Oasis without clips / 6 inch ",                                 "category_id" => 1],
            ["name" => "steel coupler Varisco / 6 inch",                                              "category_id" => 1],
            ["name" => "Steel coupler with clips 6 inch",                                             "category_id" => 1],
            ["name" => "Steel coupler without clips 6 inch",                                          "category_id" => 1],
            ["name" => "Steel Diesel Tank 1000 Ltr",                                                  "category_id" => 1],
            ["name" => "steel elbow  4  inch",                                                        "category_id" => 1],
            ["name" => "steel elbow  8  inch",                                                        "category_id" => 1],
            ["name" => "steel elbow  Hudig 6 inch",                                                   "category_id" => 1],
            ["name" => "steel elbow  Varisco 6 inch",                                                 "category_id" => 1],
            ["name" => "steel elbow 3  inch",                                                         "category_id" => 1],
            ["name" => "steel elbow 6  inch",                                                         "category_id" => 1],
            ["name" => "steel elbow geho 6 inch",                                                     "category_id" => 1],
            ["name" => "steel elbow Oasis 6 inch",                                                    "category_id" => 1],
            ["name" => "Steel Nipple 3 inch",                                                         "category_id" => 1],
            ["name" => "steel pipe 10  inch",                                                         "category_id" => 1],
            ["name" => "steel pipe 6m / 2  inch",                                                     "category_id" => 1],
            ["name" => "steel pipe 6m / 3  inch",                                                     "category_id" => 1],
            ["name" => "steel pipe 6m / 4  inch",                                                     "category_id" => 1],
            ["name" => "steel pipe 8  inch / BY METERS",                                              "category_id" => 1],
            ["name" => "Steel saw  ( hacksaw )",                                                      "category_id" => 1],
            ["name" => "strand BY METER ( brand new ) ",                                              "category_id" => 1],
            ["name" => "strand roll ( brand new ) ",                                                  "category_id" => 1],
            ["name" => "Swivel  Anchoring 140",                                                       "category_id" => 1],
            ["name" => "Swivel Anchoring 141 or 140",                                                 "category_id" => 1],
            ["name" => "Swivel C-6",                                                                  "category_id" => 1],
            ["name" => "Swivel flushing",                                                             "category_id" => 1],
            ["name" => "Swivel klemm 803",                                                            "category_id" => 1],
            ["name" => "Swivel Klemm 803 ( used )",                                                   "category_id" => 1],
            ["name" => "Swivel klemm 806",                                                            "category_id" => 1],
            ["name" => "Swivel Klemm 806 ( used )",                                                   "category_id" => 1],
            ["name" => "Table with Wood saw ( chainsaw )",                                            "category_id" => 1],
            ["name" => "TATA ( CRANE control ) USED",                                                 "category_id" => 1],
            ["name" => "Twin piston Electric Grout",                                                  "category_id" => 1],
            ["name" => "vaccum pump fan new",                                                         "category_id" => 1],
            ["name" => "Washing Machine Diesl",                                                       "category_id" => 1],
            ["name" => "Washing Machine Electic",                                                     "category_id" => 1],
            ["name" => "Water tank palstic",                                                          "category_id" => 1],
            ["name" => "Wedge (Brand new)",                                                           "category_id" => 1],
            ["name" => "Wedge (Used)",                                                                "category_id" => 1],
            ["name" => "welding machine ( steel fan ) used",                                          "category_id" => 1],
            ["name" => "Well drilling head 12  inch",                                                 "category_id" => 1],
            ["name" => "Well drilling head 17 inch",                                                  "category_id" => 1],
            ["name" => "Well drilling head 17 inch ( SCRAP )",                                        "category_id" => 1],
            ["name" => "well drilling head 24  inch",                                                 "category_id" => 1],
            ["name" => "well drilling head 6 inch",                                                   "category_id" => 1],
            ["name" => "well drilling head 8 inch",                                                   "category_id" => 1],
            ["name" => "Well drilling pipes 10m / 3 inch",                                            "category_id" => 1],
            ["name" => "Well drilling pipes 6m / 3 inch",                                             "category_id" => 1],
            ["name" => "Well drilling platform",                                                      "category_id" => 1],
            ["name" => "Wheelbarrow",                                                                 "category_id" => 1],
            ["name" => "Wood",                                                                        "category_id" => 1],
            ["name" => "Zeppelin (  hydraulic pump fan ) scrap",                                      "category_id" => 1],
            ["name" => "Zeppelin ( Boom wire Pulley ) used",                                          "category_id" => 1],
            ["name" => "Zeppelin ( engine base ) used",                                               "category_id" => 1],
            ["name" => "Zeppelin ( Idler gear ) used",                                                "category_id" => 1],
            ["name" => "Zeppelin ( Swivel / 10m ) used",                                              "category_id" => 1],
            ["name" => "Zeppelin ( Swivel / 6m ) used",                                               "category_id" => 1],
            ["name" => "Zeppelin ( water pump ) scrap",                                               "category_id" => 1],
            ["name" => "Zeppelin (Swivel casing two teeth ) used",                                    "category_id" => 1],
            ["name" => "Zeppelin swivel ( 10m )",                                                     "category_id" => 1],
            ["name" => "Zeppelin swivel ( 6m )",                                                      "category_id" => 1],
        ];
        Item::insert($items);
    }
}
